package Formularios;

import javax.swing.ImageIcon;
import javax.swing.JOptionPane;
import productosestructurapoo.Frescos;
import productosestructurapoo.Productos;

public class frmProductos extends javax.swing.JFrame {

    Productos producto;
    Frescos fresco;
    
    public frmProductos() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        btngProductos = new javax.swing.ButtonGroup();
        lblNombre = new javax.swing.JLabel();
        txtNombre = new javax.swing.JTextField();
        lblFechaCaducidad = new javax.swing.JLabel();
        ftxtFechaCaducidad = new javax.swing.JFormattedTextField();
        lblLote = new javax.swing.JLabel();
        txtLote = new javax.swing.JTextField();
        btnCrear = new javax.swing.JButton();
        btnMostrar = new javax.swing.JButton();
        rbtnFrescos = new javax.swing.JRadioButton();
        rbtnCongelados = new javax.swing.JRadioButton();
        rbtnRefrigerados = new javax.swing.JRadioButton();
        lblFechaEnvasado = new javax.swing.JLabel();
        ftxtFechaEnvasado = new javax.swing.JFormattedTextField();
        lblPais = new javax.swing.JLabel();
        cmbPais = new javax.swing.JComboBox<>();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("Gestión de Productos");
        setIconImage(new ImageIcon(getClass().getResource("/iconos/producto.png")).getImage());

        lblNombre.setText("Nombre del producto");

        lblFechaCaducidad.setText("Fecha de caducidad");

        ftxtFechaCaducidad.setFormatterFactory(new javax.swing.text.DefaultFormatterFactory(new javax.swing.text.DateFormatter(new java.text.SimpleDateFormat("dd/MM/yyyy"))));

        lblLote.setText("Lote #");

        btnCrear.setText("Crear");
        btnCrear.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnCrearActionPerformed(evt);
            }
        });

        btnMostrar.setText("Mostrar");
        btnMostrar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnMostrarActionPerformed(evt);
            }
        });

        btngProductos.add(rbtnFrescos);
        rbtnFrescos.setText("Frescos");
        rbtnFrescos.addItemListener(new java.awt.event.ItemListener() {
            public void itemStateChanged(java.awt.event.ItemEvent evt) {
                rbtnFrescosItemStateChanged(evt);
            }
        });
        rbtnFrescos.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                rbtnFrescosActionPerformed(evt);
            }
        });

        btngProductos.add(rbtnCongelados);
        rbtnCongelados.setText("Congelados");

        btngProductos.add(rbtnRefrigerados);
        rbtnRefrigerados.setText("Refrigerados");

        lblFechaEnvasado.setText("Fecha de envasado");

        ftxtFechaEnvasado.setFormatterFactory(new javax.swing.text.DefaultFormatterFactory(new javax.swing.text.DateFormatter(new java.text.SimpleDateFormat("dd/MM/yyyy"))));
        ftxtFechaEnvasado.setEnabled(false);

        lblPais.setText("País de orígen");

        cmbPais.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "<Seleccione un país>", "Guatemala", "Honduras", "Nicaragua", "Costa Rica", "Panamá" }));
        cmbPais.setEnabled(false);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(39, 39, 39)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(rbtnFrescos)
                        .addGap(18, 18, 18)
                        .addComponent(rbtnCongelados)
                        .addGap(18, 18, 18)
                        .addComponent(rbtnRefrigerados))
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(lblNombre)
                            .addComponent(lblFechaCaducidad)
                            .addComponent(lblLote))
                        .addGap(81, 81, 81)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(txtNombre, javax.swing.GroupLayout.PREFERRED_SIZE, 443, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGroup(layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                                    .addComponent(txtLote, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, 121, Short.MAX_VALUE)
                                    .addComponent(ftxtFechaCaducidad, javax.swing.GroupLayout.Alignment.LEADING))
                                .addGap(93, 93, 93)
                                .addComponent(btnCrear)
                                .addGap(18, 18, 18)
                                .addComponent(btnMostrar))))
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(lblFechaEnvasado)
                            .addComponent(lblPais))
                        .addGap(100, 100, 100)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(cmbPais, javax.swing.GroupLayout.PREFERRED_SIZE, 200, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(ftxtFechaEnvasado, javax.swing.GroupLayout.PREFERRED_SIZE, 117, javax.swing.GroupLayout.PREFERRED_SIZE))))
                .addContainerGap(31, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(24, 24, 24)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblNombre)
                    .addComponent(txtNombre, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblFechaCaducidad)
                    .addComponent(ftxtFechaCaducidad, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblLote)
                    .addComponent(txtLote, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnCrear)
                    .addComponent(btnMostrar))
                .addGap(34, 34, 34)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(rbtnFrescos)
                    .addComponent(rbtnCongelados)
                    .addComponent(rbtnRefrigerados))
                .addGap(23, 23, 23)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblFechaEnvasado)
                    .addComponent(ftxtFechaEnvasado, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(27, 27, 27)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(lblPais)
                    .addComponent(cmbPais, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(116, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnCrearActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnCrearActionPerformed
        if (!txtNombre.getText().isEmpty()){
            if (!ftxtFechaCaducidad.getText().isEmpty()){
                if (!txtLote.getText().isEmpty()){
                    producto = new Productos(this.txtNombre.getText(),this.ftxtFechaCaducidad.getText(),Integer.parseInt(this.txtLote.getText()));
                    JOptionPane.showMessageDialog(null, "Producto creado con éxito");
                }
                else{
                    JOptionPane.showMessageDialog(null, "Debe ingresar el número de lote");
                    txtLote.requestFocus();
                }
            }
            else{
                JOptionPane.showMessageDialog(null, "Debe ingresar la fecha de caducidad");
                ftxtFechaCaducidad.requestFocus();
            }
        }
        else{
            JOptionPane.showMessageDialog(null, "Debe ingresar el nombre del producto");
            txtNombre.requestFocus();
        }
    }//GEN-LAST:event_btnCrearActionPerformed

    private void btnMostrarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnMostrarActionPerformed
        producto.mostrar();
    }//GEN-LAST:event_btnMostrarActionPerformed

    private void rbtnFrescosItemStateChanged(java.awt.event.ItemEvent evt) {//GEN-FIRST:event_rbtnFrescosItemStateChanged
        if (rbtnFrescos.isSelected()){
            ftxtFechaEnvasado.setEnabled(true);
            cmbPais.setEnabled(true);
            ftxtFechaEnvasado.requestFocus();
        }
    }//GEN-LAST:event_rbtnFrescosItemStateChanged

    private void rbtnFrescosActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_rbtnFrescosActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_rbtnFrescosActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(frmProductos.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(frmProductos.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(frmProductos.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(frmProductos.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            @Override
            public void run() {
                new frmProductos().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnCrear;
    private javax.swing.JButton btnMostrar;
    private javax.swing.ButtonGroup btngProductos;
    private javax.swing.JComboBox<String> cmbPais;
    private javax.swing.JFormattedTextField ftxtFechaCaducidad;
    private javax.swing.JFormattedTextField ftxtFechaEnvasado;
    private javax.swing.JLabel lblFechaCaducidad;
    private javax.swing.JLabel lblFechaEnvasado;
    private javax.swing.JLabel lblLote;
    private javax.swing.JLabel lblNombre;
    private javax.swing.JLabel lblPais;
    private javax.swing.JRadioButton rbtnCongelados;
    private javax.swing.JRadioButton rbtnFrescos;
    private javax.swing.JRadioButton rbtnRefrigerados;
    private javax.swing.JTextField txtLote;
    private javax.swing.JTextField txtNombre;
    // End of variables declaration//GEN-END:variables
}
